#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        psarole: 'psaui'
        intport: '80'
        extport: '8555'
        image: 'richarvey/nginx-php-fpm'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: Install File
      template:
        src: /opt/psaui/templates/index.php
        dest: /opt/appdata/psaui/index.php
        force: yes
        owner: '1000'
        group: '1000'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        psa_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{psarole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting PSA Volumes'
      set_fact:
        psa_volumes:
          - '/opt/appdata/psaui/index.php:/var/www/html/index.php'
          - '/var/psautomate:/psautomate'
          - '/opt/appdata/psautomate:/log'

    - name: 'Setting PSA ENV'
      set_fact:
        psa_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{psarole}}'
      docker_container:
        name: '{{psarole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{psa_volumes}}'
        env: '{{psa_env}}'
        restart_policy: unless-stopped
        networks:
          - name: psautomate
            aliases:
              - '{{psarole}}'
        state: started
        labels: '{{psa_labels}}'
